"use client";
import Image from "next/image";
import {useCallback,useEffect,useMemo,useState} from "react";
import {ArrowUpRight,CheckCircle2,CircleAlert,FileCheck2,KeyRound,Landmark,LockKeyhole,Radio,RefreshCw,ScanSearch,ShieldCheck,Wallet} from "lucide-react";
import {connectWallet,currentAccount,isStudioNetwork,readJson,watchNetwork,watchWallet,writeContract,type Encodable} from "@/lib/chain";
import {contractExplorer,defaultContract,explorer} from "@/lib/network";
type Mode="dao"|"roles"|"mandate"|"seal"|"assess"|"execute";
type State=Record<string,unknown>;
const modes:{id:Mode;label:string;code:string}[]=[{id:"dao",label:"Establish DAO",code:"01"},{id:"roles",label:"Assign authority",code:"02"},{id:"mandate",label:"Publish mandate",code:"03"},{id:"seal",label:"Seal transaction",code:"04"},{id:"assess",label:"Run firewall",code:"05"},{id:"execute",label:"Consume permit",code:"06"}];
const initial={daoId:"atlas-dao",roleKind:"publisher",publisher:"",executor:"",mandateId:"atlas-dao.proposal-42",sourceUrl:"https://snapshot.org/#/example.eth/proposal/42",sourceRef:"proposal-42-final",mandateText:"Authorize a one-time payment for the independent security audit only. Recurring streams, grants, swaps, and unrelated transfers are prohibited.",chainId:"1",target:"0x1111111111111111111111111111111111111111",asset:"0x2222222222222222222222222222222222222222",recipient:"0x3333333333333333333333333333333333333333",maxValue:"5000",actionId:"atlas-dao.proposal-42.action-01",value:"4000",calldataDigest:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",manifest:"One-time payment for the independent security audit; no recurring stream or additional side effect.",nonce:"review-001"};
const t=(v:unknown)=>String(v??""); const n=(v:unknown)=>Number(v||0); const short=(v:string)=>v?`${v.slice(0,7)}…${v.slice(-5)}`:"—";
export default function Home(){
 const [contract,setContract]=useState(defaultContract()); const [account,setAccount]=useState(""); const [networkOk,setNetworkOk]=useState(false); const [mode,setMode]=useState<Mode>("dao"); const [f,setF]=useState(initial); const [info,setInfo]=useState<State|null>(null); const [dao,setDao]=useState<State|null>(null); const [role,setRole]=useState<State|null>(null); const [mandate,setMandate]=useState<State|null>(null); const [action,setAction]=useState<State|null>(null); const [stats,setStats]=useState<State|null>(null); const [status,setStatus]=useState("IDLE"); const [hash,setHash]=useState(""); const [error,setError]=useState("");
 const set=(k:keyof typeof initial,v:string)=>setF(p=>({...p,[k]:v}));
 const sync=useCallback(async()=>{setError("");setStatus("READING");try{const [i,s,d,r,m,a]=await Promise.all([readJson(contract,"get_contract_version"),readJson(contract,"get_stats"),readJson(contract,"get_dao",[f.daoId]),readJson(contract,"get_role",[f.daoId,account||f.publisher]),readJson(contract,"get_mandate",[f.mandateId]),readJson(contract,"get_action",[f.actionId])]);if(t(i.name)!=="MandateLock"||t(i.schema)!=="semantic-treasury-execution-firewall-v1")throw new Error("Address is not reviewed MandateLock v1");setInfo(i);setStats(s);setDao(d);setRole(r);setMandate(m);setAction(a);setStatus("SYNCED")}catch(e){setStatus("ERROR");setError(e instanceof Error?e.message:String(e))}},[contract,f.daoId,f.mandateId,f.actionId,account,f.publisher]);
 useEffect(()=>{currentAccount().then(setAccount);isStudioNetwork().then(setNetworkOk);const stopWallet=watchWallet(a=>{setAccount(a);setStatus("WALLET_CHANGED")});const stopNetwork=watchNetwork(ok=>{setNetworkOk(ok);setStatus(ok?"NETWORK_READY":"WRONG_NETWORK")});return()=>{stopWallet();stopNetwork()}},[]);
 const authority=t(dao?.authority).toLowerCase()===account.toLowerCase(); const publisher=t(mandate?.publisher||f.publisher).toLowerCase()===account.toLowerCase()||role?.publisher===true; const executor=t(action?.executor||f.executor).toLowerCase()===account.toLowerCase();
 const gate=useMemo(()=>{if(!account)return [false,"Connect a funded StudioNet wallet."] as const;if(!networkOk)return [false,"Switch wallet to GenLayer StudioNet · 61999."] as const;if(mode==="dao")return [dao?.exists!==true,"Any wallet may claim an unused DAO namespace."] as const;if(mode==="roles")return [authority,"Only namespace authority assigns scoped roles."] as const;if(mode==="mandate")return [role?.publisher===true,"Registered publisher authenticates the mandate snapshot."] as const;if(mode==="seal")return [publisher&&mandate?.exists===true&&!t(mandate.open_action_id),"Publisher binds one exact transaction intent."] as const;if(mode==="assess")return [action?.status==="PENDING_ASSESSMENT","Any wallet may trigger validator assessment."] as const;return [executor&&action?.status==="AUTHORIZED","Only assigned, still-registered executor may consume."] as const},[account,networkOk,mode,dao,authority,role,publisher,mandate,action,executor]);
 async function submit(){setError("");if(!gate[0])return setError(gate[1]);let method="";let args:Encodable[]=[];if(mode==="dao"){method="create_dao";args=[f.daoId]}else if(mode==="roles"){method=f.roleKind==="publisher"?"set_publisher":"set_executor";args=[f.daoId,f.roleKind==="publisher"?f.publisher:f.executor,true]}else if(mode==="mandate"){method="publish_mandate";args=[f.mandateId,f.daoId,f.sourceUrl,f.sourceRef,f.mandateText,BigInt(f.chainId),f.target,f.asset,f.recipient,BigInt(f.maxValue)]}else if(mode==="seal"){method="seal_action";args=[f.actionId,f.mandateId,BigInt(f.chainId),f.target,f.asset,f.recipient,BigInt(f.value),f.calldataDigest,f.manifest,f.executor,f.nonce]}else if(mode==="assess"){method="assess_action";args=[f.actionId]}else{method="consume_permit";args=[f.actionId,f.calldataDigest,f.nonce]}try{const h=await writeContract(contract,account,method,args,(s,x)=>{setStatus(s);if(x)setHash(x)});setHash(h);const before=mode==="dao"?dao:mode==="roles"?role:mode==="mandate"?mandate:action;await sync();const fresh=mode==="dao"?await readJson(contract,"get_dao",[f.daoId]):mode==="roles"?await readJson(contract,"get_role",[f.daoId,f.roleKind==="publisher"?f.publisher:f.executor]):mode==="mandate"?await readJson(contract,"get_mandate",[f.mandateId]):await readJson(contract,"get_action",[f.actionId]);if(JSON.stringify(fresh)===JSON.stringify(before))throw new Error("Finalized, but authoritative state did not change");const ok=mode==="dao"?fresh.exists===true:mode==="roles"?(f.roleKind==="publisher"?fresh.publisher===true:fresh.executor===true):mode==="mandate"?fresh.exists===true:mode==="seal"?fresh.status==="PENDING_ASSESSMENT":mode==="assess"?["AUTHORIZED","BLOCKED"].includes(t(fresh.status)):fresh.status==="CONSUMED";if(!ok)throw new Error("Finalized, but expected state transition was not confirmed");setStatus("VERIFIED")}catch(e){setStatus("ERROR");setError(e instanceof Error?e.message:String(e))}}
 const selected=modes.find(x=>x.id===mode)!;
 return <main><header><a className="brand" href="#top"><Image src="/mandatelock-logo.png" alt="MandateLock" width={52} height={52}/><span><b>MANDATELOCK</b><small>TREASURY EXECUTION FIREWALL</small></span></a><div className="net"><Radio/> STUDIONET · 61999</div><button className="wallet" onClick={async()=>{try{setAccount(await connectWallet());setNetworkOk(true);setError("")}catch(e){setNetworkOk(false);setError(e instanceof Error?e.message:String(e))}}}><Wallet/>{account?(networkOk?short(account):"WRONG NETWORK"):"CONNECT WALLET"}</button></header>
 <section className="hero" id="top"><div><p className="kicker">GOVERNANCE INTENT → EXECUTION PERMIT</p><h1>A vote is not<br/><em>a blank cheque.</em></h1><p className="lede">Bind treasury execution to the exact proposal scope. Semantic consensus catches hidden intent; deterministic checks lock chain, target, asset, recipient, value and calldata.</p><div className="proofline"><span>AUTHENTICATED MANDATE</span><i/><span>VALIDATOR JUDGMENT</span><i/><span>SINGLE-USE PERMIT</span></div></div><div className="heroMark"><Image src="/mandatelock-logo.png" alt="Governance mandate shield" width={500} height={500} priority/><div className="stamp"><ShieldCheck/><b>BOUND<br/>BY INTENT</b></div></div></section>
 <section className="locator"><label><span>ACTIVE CONTRACT</span><input value={contract} onChange={e=>setContract(e.target.value)} placeholder="0x…"/></label><label><span>DAO / MANDATE / ACTION</span><div><input value={f.daoId} onChange={e=>set("daoId",e.target.value)}/><input value={f.mandateId} onChange={e=>set("mandateId",e.target.value)}/><input value={f.actionId} onChange={e=>set("actionId",e.target.value)}/></div></label><button onClick={()=>sync()}><RefreshCw/>SYNC LEDGER</button></section>
 <section className="shell"><nav><p>EXECUTION DOSSIER</p>{modes.map(x=><button className={mode===x.id?"active":""} onClick={()=>setMode(x.id)} key={x.id}><i>{x.code}</i><span>{x.label}</span></button>)}<aside><LockKeyhole/><b>Deployer neutral</b><span>Authority begins only when a wallet claims its own namespace.</span></aside></nav><article><div className="casehead"><div><small>PROCEDURE {selected.code}</small><h2>{selected.label}</h2></div><span className={`state ${t(action?.status).toLowerCase()}`}>{t(action?.status||mandate?.active&&"MANDATE ACTIVE"||"NOT SYNCED")}</span></div><div className="form">{mode==="dao"&&<Field label="DAO NAMESPACE" value={f.daoId} set={v=>set("daoId",v)}/>} {mode==="roles"&&<><Field label="ROLE KIND (publisher / executor)" value={f.roleKind} set={v=>set("roleKind",v)}/><Field label="PUBLISHER WALLET" value={f.publisher} set={v=>set("publisher",v)}/><Field label="EXECUTOR WALLET" value={f.executor} set={v=>set("executor",v)}/><p className="hint">Set role kind to publisher or executor, then submit the corresponding wallet. Reviewer can assign their own wallets inside a namespace they create.</p></>}{mode==="mandate"&&<><Field label="SOURCE URL" value={f.sourceUrl} set={v=>set("sourceUrl",v)}/><Field label="SOURCE REVISION" value={f.sourceRef} set={v=>set("sourceRef",v)}/><Area label="AUTHENTICATED MANDATE TEXT" value={f.mandateText} set={v=>set("mandateText",v)}/><Scope f={f} set={set} max/></>}{mode==="seal"&&<><Scope f={f} set={set}/><Field label="CALLDATA SHA-256" value={f.calldataDigest} set={v=>set("calldataDigest",v)}/><Field label="ASSIGNED EXECUTOR" value={f.executor} set={v=>set("executor",v)}/><Field label="NONCE" value={f.nonce} set={v=>set("nonce",v)}/><Area label="ACTION MANIFEST" value={f.manifest} set={v=>set("manifest",v)}/></>}{mode==="assess"&&<Decision icon={<ScanSearch/>} title="Independent semantic firewall" body="Validators judge purpose, prohibitions and hidden side effects only after exact structured scope passes."/>}{mode==="execute"&&<Decision icon={<KeyRound/>} title="Consume the exact capability" body="Rechecks executor registration, revision, calldata digest and nonce before recording one consumption."/>}</div><div className="action"><div><small>CURRENT AUTHORITY</small><b>{authority?"DAO AUTHORITY":publisher?"MANDATE PUBLISHER":executor?"ASSIGNED EXECUTOR":"REVIEWER / TRIGGER"}</b><span>{gate[1]}</span></div><button disabled={!gate[0]} onClick={submit}><FileCheck2/>{mode==="assess"?"RUN FIREWALL":mode==="execute"?"CONSUME PERMIT":"SUBMIT ON-CHAIN"}</button></div>{(error||status!=="IDLE")&&<div className={`tx ${error?"bad":""}`}>{error?<CircleAlert/>:<CheckCircle2/>}<div><b>{error?"ACTION STOPPED":status}</b><span>{error||"Success is shown only after finality and matching contract readback."}</span></div>{hash&&<a href={explorer(hash)} target="_blank">EXPLORER <ArrowUpRight/></a>}</div>}</article></section>
 <section className="ledger"><div><small>AUTHORITATIVE READBACK</small><h2>Execution ledger</h2><p>Never inferred from wallet approval or optimistic UI.</p></div><Metric label="DAO" value={t(dao?.dao_id||f.daoId)} note={short(t(dao?.authority))}/><Metric label="MANDATE" value={mandate?.exists?`REVISION ${n(mandate.revision)}`:"NOT FOUND"} note={short(t(mandate?.mandate_digest))}/><Metric label="VERDICT" value={t(action?.verdict||"PENDING")} note={(action?.violations as string[]||[]).join(", ")||"no violations"}/><Metric label="PERMIT" value={t(action?.status||"NONE")} note={short(t(action?.permit_digest))}/></section>
 <section className="identity"><div><Landmark/><b>{n(stats?.daos)} DAOs</b></div><div><FileCheck2/><b>{n(stats?.mandates)} MANDATES</b></div><div><KeyRound/><b>{n(stats?.open_permits)} OPEN PERMITS</b></div><div><LockKeyhole/><b>{n(stats?.consumed)} CONSUMED</b></div><a href={contract?contractExplorer(contract):undefined} target="_blank">CONTRACT <ArrowUpRight/></a></section><footer><b>MANDATELOCK</b><span>Semantic scope · Exact bindings · Single-use authority</span><span>{t(info?.schema||"Connect reviewed contract")}</span></footer></main>
}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="field"><span>{label}</span><input value={value} onChange={e=>set(e.target.value)}/></label>}
function Area({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="field wide"><span>{label}</span><textarea value={value} onChange={e=>set(e.target.value)}/></label>}
function Scope({f,set,max=false}:{f:typeof initial;set:(k:keyof typeof initial,v:string)=>void;max?:boolean}){return <><Field label="CHAIN ID" value={f.chainId} set={v=>set("chainId",v)}/><Field label="TARGET" value={f.target} set={v=>set("target",v)}/><Field label="ASSET" value={f.asset} set={v=>set("asset",v)}/><Field label="RECIPIENT" value={f.recipient} set={v=>set("recipient",v)}/><Field label={max?"MAX VALUE":"ACTION VALUE"} value={max?f.maxValue:f.value} set={v=>set(max?"maxValue":"value",v)}/></>}
function Decision({icon,title,body}:{icon:React.ReactNode;title:string;body:string}){return <div className="decision">{icon}<div><b>{title}</b><p>{body}</p><span>COMPLIANT</span><span>SCOPE_EXCEEDED</span><span>CONTRADICTORY</span><span>INSUFFICIENT</span></div></div>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="metric"><small>{label}</small><b>{value}</b><span>{note}</span></div>}

